INSERT INTO `允许使用多字母斜体表示的变量` VALUES (' 均方根误差 ', 'RMSE', '0');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('优化土壤调节植被指数', 'OSAVI', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('作物氮反应指数 ', 'NRI', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('作物蒸发蒸腾量 ', 'ETc ', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('修正土壤调节植被指数', 'MSAVI', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('光合有效辐射量', 'PAR', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('光能利用效率 ', 'RUE', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('参考作物蒸发蒸腾量 ', 'Eto', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('可见光大气阻抗植被指数', 'VARI', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('叶面积指数', 'LAI', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('土壤电导率 ', 'EC', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('平均相对误差 ', 'MRE', NULL);
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('归一化差异水体指数', 'MNDWI', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('归一化植被指数 ', 'NDVI', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('总蒸散量 ', 'ET', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('最小预测残差平方和', 'PRESS', '0');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('条件植被温度指数 ', 'VTCI', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('标准叶绿素指数', 'NPCI', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('校正集标准误差 ', 'SEC', '0');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('植被面积指数', 'PAI', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('比值植被指数', 'RVI', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('水分利用效率 ', 'WUE', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('绿色比值植被指数 ', 'GRVI', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('耗水量 ', 'ET', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('聚集度系数 ', 'CI', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('肥料偏生产力 ', 'PFP', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('茎面积指数', 'SAI', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('转化叶绿素吸收反射指数', 'TCARI', '1');
INSERT INTO `允许使用多字母斜体表示的变量` VALUES ('预测集标准误差 ', 'SEP', '0');
