INSERT INTO `变量名称、符号与单位` VALUES ('长度', 'L', 'm, cm, mm');
INSERT INTO `变量名称、符号与单位` VALUES ('宽度', 'b', NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('高度', 'h', NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('厚度', 'd,δ', NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('半径', 'r, R', NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('直径', 'd ,D', NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('距离', 'd, r', NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('位移', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('角', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('角位移', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('曲率', 'κ', 'm‐1');
INSERT INTO `变量名称、符号与单位` VALUES ('曲率半径', 'ρ', 'm');
INSERT INTO `变量名称、符号与单位` VALUES ('面积', 'A,(S)', 'mm2/m2/hm2/km2');
INSERT INTO `变量名称、符号与单位` VALUES ('体积', 'V', 'mm3/m3/hm3/km3');
INSERT INTO `变量名称、符号与单位` VALUES ('时间', 't', 'a,d,h,min,s');
INSERT INTO `变量名称、符号与单位` VALUES ('速度', 'v, c, u, w', 'm/s ,km/h');
INSERT INTO `变量名称、符号与单位` VALUES ('加速度', 'a', 'm/s2');
INSERT INTO `变量名称、符号与单位` VALUES ('角速度', 'ω', 'rad/s');
INSERT INTO `变量名称、符号与单位` VALUES ('角加速度', 'α', 'rad/s');
INSERT INTO `变量名称、符号与单位` VALUES ('转速', 'n', 'r/min,r/s');
INSERT INTO `变量名称、符号与单位` VALUES ('相速度', 'c ,v', 'm/s');
INSERT INTO `变量名称、符号与单位` VALUES ('群速度', 'cg ,vg', 'm/s');
INSERT INTO `变量名称、符号与单位` VALUES ('周期', 'T', 's');
INSERT INTO `变量名称、符号与单位` VALUES ('频率', 'f ,υ', 'Hz');
INSERT INTO `变量名称、符号与单位` VALUES ('波长', 'λ', 'm');
INSERT INTO `变量名称、符号与单位` VALUES ('波数', 'σ', 'm‐1');
INSERT INTO `变量名称、符号与单位` VALUES ('角频率', 'ω', 'rad/s ,s‐1');
INSERT INTO `变量名称、符号与单位` VALUES ('质量', 'm', 'kg');
INSERT INTO `变量名称、符号与单位` VALUES ('密度', 'ρ', 'kg/m3');
INSERT INTO `变量名称、符号与单位` VALUES ('力', 'F', 'N');
INSERT INTO `变量名称、符号与单位` VALUES ('重力', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('重量', 'W(P,G)', 'N');
INSERT INTO `变量名称、符号与单位` VALUES ('压力', 'P', 'N');
INSERT INTO `变量名称、符号与单位` VALUES ('压强（压力）', 'p（小写）', 'Pa');
INSERT INTO `变量名称、符号与单位` VALUES ('转动惯量', 'J,(I)', 'kg·m2');
INSERT INTO `变量名称、符号与单位` VALUES ('（惯性矩）', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('动量', 'P', 'kg·m/s');
INSERT INTO `变量名称、符号与单位` VALUES ('动量矩', 'L', 'kg·m2/s');
INSERT INTO `变量名称、符号与单位` VALUES ('力矩', 'M', 'N·m');
INSERT INTO `变量名称、符号与单位` VALUES ('转矩扭矩', 'M,T', 'N·m');
INSERT INTO `变量名称、符号与单位` VALUES ('力偶矩', 'M', 'N·m');
INSERT INTO `变量名称、符号与单位` VALUES ('正应力', 'σ', 'Pa');
INSERT INTO `变量名称、符号与单位` VALUES ('切应力', 'τ', NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('线应变', 'ε,e', NULL);
INSERT INTO `变量名称、符号与单位` VALUES (NULL, NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('切应变', 'γ', NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('体应变', 'θ', NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('泊松比', 'μ, ν', NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('弹性模量', 'E', 'Pa');
INSERT INTO `变量名称、符号与单位` VALUES ('剪切模量', 'Κ', 'Pa');
INSERT INTO `变量名称、符号与单位` VALUES ('摩擦因数', 'μ,f', '1');
INSERT INTO `变量名称、符号与单位` VALUES ('粘度', 'η(μ)', 'Pa·s');
INSERT INTO `变量名称、符号与单位` VALUES ('运动粘度', 'ν', 'm2/s');
INSERT INTO `变量名称、符号与单位` VALUES ('表面张力', 'Υ,σ', 'N/m');
INSERT INTO `变量名称、符号与单位` VALUES ('功', 'W,(A)', 'J');
INSERT INTO `变量名称、符号与单位` VALUES ('势能', 'EP, (V)', 'J');
INSERT INTO `变量名称、符号与单位` VALUES ('动能', 'EK,(T)', 'J');
INSERT INTO `变量名称、符号与单位` VALUES ('功率', 'P', 'W');
INSERT INTO `变量名称、符号与单位` VALUES ('效率', 'η', NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('质量流量', 'qm', 'kg/s');
INSERT INTO `变量名称、符号与单位` VALUES ('体积流量', 'qv', 'm3/s');
INSERT INTO `变量名称、符号与单位` VALUES ('质量分数', NULL, '1，%');
INSERT INTO `变量名称、符号与单位` VALUES ('体积分数', NULL, '1，%');
INSERT INTO `变量名称、符号与单位` VALUES ('质量浓度', NULL, 'kg/m3');
INSERT INTO `变量名称、符号与单位` VALUES ('浓度', NULL, 'mol/L');
INSERT INTO `变量名称、符号与单位` VALUES ('物质的量', NULL, 'mol');
INSERT INTO `变量名称、符号与单位` VALUES ('刚度', NULL, 'N/m');
INSERT INTO `变量名称、符号与单位` VALUES ('阻尼系数', 'δ', 's‐1');
INSERT INTO `变量名称、符号与单位` VALUES ('容重', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('含水率', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('坚实度', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('波长', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('波段', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('热力学温度', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('摄氏温度', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('线膨胀系数', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('热，热量', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('热导率', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('表面传热系数', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('比热容', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('熵', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('比熵', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('焓', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('比焓', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('电流', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('电压', 'I', NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('电阻', 'U,V', NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('电容', 'R', NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('电场强度', 'C', NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('电势', NULL, NULL);
INSERT INTO `变量名称、符号与单位` VALUES ('介电常数', NULL, NULL);
