INSERT INTO `常见资助项目名称` VALUES ('中国博士后科学基金项目 ');
INSERT INTO `常见资助项目名称` VALUES ('中国科学院百人计划项目');
INSERT INTO `常见资助项目名称` VALUES ('中国科学院知识创新项目 ');
INSERT INTO `常见资助项目名称` VALUES ('中国科学院重点资助项目 ');
INSERT INTO `常见资助项目名称` VALUES ('中央高校基本科研业务费专项资金项目');
INSERT INTO `常见资助项目名称` VALUES ('农业部公益性行业科研专项 ');
INSERT INTO `常见资助项目名称` VALUES ('农业部引进国际先进农业科学技术计划（948计划）项目');
INSERT INTO `常见资助项目名称` VALUES ('创新研究群体科学基金项目 ');
INSERT INTO `常见资助项目名称` VALUES ('国土资源部公益性行业科研专项 ');
INSERT INTO `常见资助项目名称` VALUES ('国土资源部财政预算项目 ');
INSERT INTO `常见资助项目名称` VALUES ('国家优秀青年科学基金项目 “十二五”国家科技支撑计划项目 ');
INSERT INTO `常见资助项目名称` VALUES ('国家国际科技合作专项 ');
INSERT INTO `常见资助项目名称` VALUES ('国家杰出青年科学基金项目');
INSERT INTO `常见资助项目名称` VALUES ('国家自然科学基金项目（面上项目，重点项目，重大项目） ');
INSERT INTO `常见资助项目名称` VALUES ('国家重点基础研究发展计划（973计划）项目 ');
INSERT INTO `常见资助项目名称` VALUES ('国家重点研发计划项目');
INSERT INTO `常见资助项目名称` VALUES ('国家高技术研究发展计划（863计划）项目 ');
INSERT INTO `常见资助项目名称` VALUES ('国防基础研究项目 ');
INSERT INTO `常见资助项目名称` VALUES ('国防预先研究项目');
INSERT INTO `常见资助项目名称` VALUES ('教育部新世纪优秀人才项目');
INSERT INTO `常见资助项目名称` VALUES ('教育部留学回国人员科研启动基金项目 ');
INSERT INTO `常见资助项目名称` VALUES ('水利部公益性行业科研专项');
INSERT INTO `常见资助项目名称` VALUES ('江苏省产学研前瞻性联合研究项目 ');
INSERT INTO `常见资助项目名称` VALUES ('江苏省农业科技自主创新资金项目 ');
INSERT INTO `常见资助项目名称` VALUES ('江苏高校优势学科建设工程项目 ');
INSERT INTO `常见资助项目名称` VALUES ('海外青年学者合作研究基金项目 ');
INSERT INTO `常见资助项目名称` VALUES ('科技部科技型中小企业创新基金项目 ');
INSERT INTO `常见资助项目名称` VALUES ('高等学校博士学科点专项科研基金项目 ');
