INSERT INTO `常见工作单位规范写法` VALUES (' 南京农业大学工学院', 'College of Engineering, Nanjing Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES (' 南京农业大学工学院/江苏省智能化农业装备重点实验室', 'College of Engineering, Nanjing Agricultural University， Key Laboratory of Intelligent Agricultural Equipment in Jiangsu Province');
INSERT INTO `常见工作单位规范写法` VALUES (' 沈阳农业大学水利学院', 'College of Water Conservancy, Shenyang Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES (' 浙江工业大学海洋学院', 'Ocean College, Zhejiang University of Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('上海交通大学机器人研究所', 'Research Institute of Robotics, Shanghai Jiaotong University');
INSERT INTO `常见工作单位规范写法` VALUES ('上海交通大学机械与动力工程学院', 'School of Mechanical Engineering, Shanghai Jiao Tong University');
INSERT INTO `常见工作单位规范写法` VALUES ('东北农业大学工程学院', 'College of Engineering, Northeast Agricultural University ');
INSERT INTO `常见工作单位规范写法` VALUES ('东北农业大学水利与土木工程学院', 'School of Water Conservancy and Civil Engineering, Northeast Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('东北农业大学食品学院 ', 'College of food Science，Northeast Agricultural University ');
INSERT INTO `常见工作单位规范写法` VALUES ('东北大学机械工程与自动化学院', 'School of Mechanical Engineering and Automation, Northeastern University');
INSERT INTO `常见工作单位规范写法` VALUES ('东北电力大学机械工程学院', 'School of Mechanical Engineering, Northeast Dianli University');
INSERT INTO `常见工作单位规范写法` VALUES ('东北电力大学自动化工程学院', 'School of Automation Engineering, Northeast Dianli University');
INSERT INTO `常见工作单位规范写法` VALUES ('东南大学机械工程学院', 'School of Mechanical Engineering, Southeast University');
INSERT INTO `常见工作单位规范写法` VALUES ('中南大学机电工程学院', 'College of Mechanical and Electrical Engineering, Central South University');
INSERT INTO `常见工作单位规范写法` VALUES ('中国农业大学信息与电气工程学院', 'College of Information and Electrical Engineering, China Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('中国农业大学工学院', 'College of Engineering, China Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('中国农业大学水利与土木工程学院', 'College of Water Resources and Civil Engineering, China Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('中国农业大学资源与环境学院', 'College of Resources and Environmental Sciences, China Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('中国农业大学食品科学与营养工程学院', 'College of Food Science and Nutritional Engineering, China Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('中国农业机械化科学研究院', 'Chinese Academy of Agricultural Mechanization Sciences');
INSERT INTO `常见工作单位规范写法` VALUES ('中国农业科学院农业信息研究所', 'Agricultural Information Institute, Chinese Academy of Agricultural Sciences');
INSERT INTO `常见工作单位规范写法` VALUES ('中国农业科学院农业环境与可持续发展研究所', 'Institute of Environment and Sustainable Development in Agriculture, Chinese Academy of Agriculture Sciences');
INSERT INTO `常见工作单位规范写法` VALUES ('中国农业科学院农业资源与农业区划研究所', 'Institute of Agricultural Resources and Regional Planning, Chinese Academy of Agricultural Sciences');
INSERT INTO `常见工作单位规范写法` VALUES ('中国农业科学院农产品加工研究所', 'Institute of Agro‐Products Processing Science and Technology, Chinese Academy of Agriculture Sciences');
INSERT INTO `常见工作单位规范写法` VALUES ('中国农业科学院农田灌溉研究所', 'Farmland Irrigation Research Institute, Chinese Academy of Agricultural Sciences');
INSERT INTO `常见工作单位规范写法` VALUES ('中国水利水电科学院研究院', 'China Institute of Water Resources and Hydropower Research');
INSERT INTO `常见工作单位规范写法` VALUES ('中国科学院地理科学与资源研究所', 'Institute of Geographic Sciences and Natural Resources Research, Chinese Academy of Sciences');
INSERT INTO `常见工作单位规范写法` VALUES ('中国科学院水利部水土保持研究所黄土高原土壤侵蚀与旱地农业国家重点实验室', 'State Key Laboratory of Soil Erosion and Dry‐land Farming on the Loess Plateau, Institute of Soil and Water Conservation,Chinese Academy of Sciences and Ministry of Water resource');
INSERT INTO `常见工作单位规范写法` VALUES ('中国科学院遥感与数字地球研究所', 'Institute of Remote Sensing and Digital Earth, Chinese Academy of Sciences');
INSERT INTO `常见工作单位规范写法` VALUES ('中国计量大学机电工程学院', 'College of Mechanical and Electrical Engineering, China Jiliang University');
INSERT INTO `常见工作单位规范写法` VALUES ('中国计量大学生命科学学院', 'College of Life Sciences, Chian Jiliang University');
INSERT INTO `常见工作单位规范写法` VALUES ('中国计量大学计量测试工程学院', 'College of Metrology and Measurement Engineering, China Jiliang University');
INSERT INTO `常见工作单位规范写法` VALUES ('内蒙古农业大学机电工程学院', 'College of Mechanical and Electrical Engineering, Inner Mongolia Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('内蒙古农业大学水利与土木建筑工程学院', 'College of Water Conservation and Civil Engineering, Inner Mongolia Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('内蒙古农业大学食品科学与工程学院', 'College of Food Science and Engineering, Inner Mongolia Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('农业装备工程学院（农业工程研究院）', 'School of Agricultural Equipment Engineering,Institute of Agricultural Engineering,Jiangsu niversity ');
INSERT INTO `常见工作单位规范写法` VALUES ('农业部规划设计研究院', 'Chinese Academy of Agriculture Engineering');
INSERT INTO `常见工作单位规范写法` VALUES ('北京农业信息技术研究中心', 'Beijing Research Center for Information Technology in Agriculture');
INSERT INTO `常见工作单位规范写法` VALUES ('北京师范大学地理学与遥感科学学院', 'School of Geography, Beijing Normal University');
INSERT INTO `常见工作单位规范写法` VALUES ('北京林业大学工学院', 'School of Technology, Beijing Forestry University');
INSERT INTO `常见工作单位规范写法` VALUES ('北京林业大学林学院', 'College of Forestry, Beijing Forestry University');
INSERT INTO `常见工作单位规范写法` VALUES ('北京林业大学水土保持学院', 'School of Soil and Water Conservation, Beijing Forestry University');
INSERT INTO `常见工作单位规范写法` VALUES ('北京理工大学机械与车辆学院', 'School of Mechanical Engineering, Beijing Institute of Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('北京理工大学自动化学院', 'School of Automation, Beijing Institute of Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('北京科技大学机械工程学院', 'School of Mechanical Engineering, University of Science and Technology Beijing');
INSERT INTO `常见工作单位规范写法` VALUES ('北京科技大学能源与环境工程学院', 'School of Energy and Environmental Engineering, University of Science and Technology Beijing');
INSERT INTO `常见工作单位规范写法` VALUES ('北京航空航天大学仪器科学与光电工程学院', 'School of Instrumentation Science and Optoelectronics Engineering, Beihang University');
INSERT INTO `常见工作单位规范写法` VALUES ('北京航空航天大学仿生与微纳生物制造技术研究中心', 'Bionics and Biologic Micro/nano‐bio‐manufacturing Research Center, Beihang University');
INSERT INTO `常见工作单位规范写法` VALUES ('北京航空航天大学机械工程及自动化学院', 'School of Mechanical Engineering and Automation, Beihang University');
INSERT INTO `常见工作单位规范写法` VALUES ('北京航空航天大学自动化科学与电气工程学院', 'School of Automation Science and Electrical Engineering, Beihang University');
INSERT INTO `常见工作单位规范写法` VALUES ('北京邮电大学自动化学院', 'School of Automation, Beijing University of Posts and Telecommunications');
INSERT INTO `常见工作单位规范写法` VALUES ('北方工业大学机电工程学院', 'College of Mechanical and Electrical Engineering, North China University of Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('华中农业大学工学院', 'College of Engineering, Huazhong Agricultural University,');
INSERT INTO `常见工作单位规范写法` VALUES ('华中农业大学资源与环境学院', 'College of Resources and Environment, Huazhong Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('华中农业大学食品科学技术学院', 'College of Food Science and Technology, Huazhong Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('华南农业大学南方农业机械与装备关键技术省部共建教育部重点实验室', 'Key Laboratory of Key Technology on Agricultural Machine and Equipment, Ministry of Education, South China Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('华南农业大学工程学院                                        ', 'College of Engineering, South China Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('华南农业大学材料与能源学院', 'College of Materials & Energy,South China Agricultural University ');
INSERT INTO `常见工作单位规范写法` VALUES ('南京农业大学/国家信息农业工程技术中心，江苏省信息农业高技术研究重点实验室   ', 'National Engineering and Technology Center for Agriculture/Jiangsu key laboratory for Information Agriculture, Nanjing Agriculture University ');
INSERT INTO `常见工作单位规范写法` VALUES ('南京农业大学工学院/江苏省现代设施农业技术与装备工程实验室   ', 'College of Engineering, Engineering Laboratory of Modern Facility Agriculture Technology and Equipment in Jiangsu Province, Nanjing Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('南京农业大学食品科技学院', 'College of Food Science and Technology, Nanjing Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('南京工业大学机械与动力工程学院', 'School of Mechanical and Power Engineering, Nanjing University of Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('南京林业大学机械电子工程学院', 'College of Mechanical and Electronic Engineering, Nanjing Forestry University ');
INSERT INTO `常见工作单位规范写法` VALUES ('南京理工大学机械工程学院', 'School of Mechanical Engineering, Nanjing University of Science and Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('南京航空航天大学机电学院', 'College of Mechanical and Electronic Engineering, Nanjing University of Aeronautics and Astronautics');
INSERT INTO `常见工作单位规范写法` VALUES ('吉林大学生物与农业工程学院', 'College of Biological and Agricultural Engineering, Jilin University');
INSERT INTO `常见工作单位规范写法` VALUES ('国土资源部土地整治中心', 'The ministry of land and resources land management center ');
INSERT INTO `常见工作单位规范写法` VALUES ('国家农业信息化工程技术研究中心', 'National Engineering Research Center for Information Technology in Agriculture');
INSERT INTO `常见工作单位规范写法` VALUES ('国家农业智能装备工程技术研究中心', 'National Engineering Research Center of Intelligent Equipment for Agriculture');
INSERT INTO `常见工作单位规范写法` VALUES ('国家林业局北京林业机械研究所', 'Beijing Forestry Machinery Research Institute of the State Forestry Administration');
INSERT INTO `常见工作单位规范写法` VALUES ('太原理工大学机械工程学院', 'College of Mechanical Engineering, Taiyuan University of Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('太原理工大学水利科学与工程学院', 'College of Water Resource Science and Engineering, Taiyuan University of Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('安徽农业大学工学院', 'School of Engineering, Anhui Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('安徽农业大学茶与食品科技学院', 'College of Tea & Food Science and Technology, Anhui Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('山东农业大学机械与电子工程学院', 'College of Mechanical and Electronic Engineering, Shandong Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('山东农业大学水利土木工程学院', 'College of Water Conservancy and Civil Engineering, Shandong Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('山东理工大学农业工程与食品科学学院', 'School of Agricultural Engineering and Food Science, Shandong University of Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('常州大学信息科学与工程学院', 'School of Information Science and Engineering, Changzhou University');
INSERT INTO `常见工作单位规范写法` VALUES ('常州大学机械工程学院', 'School of Mechanical Engineering, Changzhou University');
INSERT INTO `常见工作单位规范写法` VALUES ('扬州大学机械工程学院', 'College of Mechanical Engineering, Yangzhou University');
INSERT INTO `常见工作单位规范写法` VALUES ('扬州大学水利与能源动力工程学院', 'School of Hydraulic Energy and Power Engineering, Yangzhou University');
INSERT INTO `常见工作单位规范写法` VALUES ('昆明理工大学机电工程学院', 'Faculty of Mechanical and Electrical Engineering, Kunming University of Science and Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('昆明理工大学现代农业工程学院', 'Faculty of Modern Agricultural Engineering, Kunming University of Science and Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('机械科学研究总院', 'China Academy of Machinery Science and Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('武汉大学动力与机械学院', 'School of Power and Mechanical Engineering, Wuhan University');
INSERT INTO `常见工作单位规范写法` VALUES ('江南大学机械工程学院', 'School of Mechanical Engineering, Jiangnan University');
INSERT INTO `常见工作单位规范写法` VALUES ('江南大学食品学院', 'School of Food Science and Technology, JiangNan University');
INSERT INTO `常见工作单位规范写法` VALUES ('江苏大学流体机械工程技术研究中心  ', 'Research Center of Fluid Machinery Engineering and Technology，Jiangsu University ');
INSERT INTO `常见工作单位规范写法` VALUES ('江苏大学电气信息工程学院', 'School of Electrical and Information Engineering, Jiangsu University ');
INSERT INTO `常见工作单位规范写法` VALUES ('江苏大学能源与动力工程学院', 'School of Energy and Power Engineering, Jiangsu University');
INSERT INTO `常见工作单位规范写法` VALUES ('江苏大学食品与生物工程学院', 'School of Food and Biological Engineering, Jiangsu University');
INSERT INTO `常见工作单位规范写法` VALUES ('沈阳农业大学工程学院  ', 'College of Engineering，Shenyang Agricultural University ');
INSERT INTO `常见工作单位规范写法` VALUES ('沈阳农业大学食品学院   ', 'College of Food，Shenyang Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('沈阳工业大学机械工程学院', 'School of Mechanical Engineering, Shenyang University of Technology ');
INSERT INTO `常见工作单位规范写法` VALUES ('河北工业大学机械工程学院', 'School of Mechanical Engineering, Hebei University of Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('河北工业大学电气工程学院', 'School of Electrical Engineering, Hebei University of Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('河海大学水利水电学院', 'College of Water Conservancy and Hydropower, HoHai University');
INSERT INTO `常见工作单位规范写法` VALUES ('河海大学水文水资源与水利工程科学国家重点实验室', 'State Key Laboratory of Hydrology‐Water Resources and Hydraulic Engineering, HoHai University');
INSERT INTO `常见工作单位规范写法` VALUES ('河海大学能源与电气学院', 'College of Energy and Electrical Engineering, Hohai University');
INSERT INTO `常见工作单位规范写法` VALUES ('浙江大学制冷与低温研究所   ', 'Institute of Refrigeration and Cryogenics，Zhejiang University');
INSERT INTO `常见工作单位规范写法` VALUES ('浙江大学宁波理工学院', 'Ningbo Institute of Technology. Zhejiang University');
INSERT INTO `常见工作单位规范写法` VALUES ('浙江大学机械工程学院', 'College of Mechanical Engineering, Zhejiang University');
INSERT INTO `常见工作单位规范写法` VALUES ('浙江大学流体动力与机电系统国家重点实验室', 'State Key Laboratory of Fluid Power and Mechatronic Systems, Zhejiang University');
INSERT INTO `常见工作单位规范写法` VALUES ('浙江大学现代制造工程研究所', 'Institute of Advanced Manufacturing Engineering, Zhejiang University ');
INSERT INTO `常见工作单位规范写法` VALUES ('浙江大学生物系统工程与食品科学学院', 'College of Biosystems Engineering and Food Science, Zhejiang University');
INSERT INTO `常见工作单位规范写法` VALUES ('浙江工业大学机械工程学院', 'College of Mechanical Engineering, Zhejiang University of Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('浙江工业大学特种装备制造与先进加工技术教育部重点实验室', 'Key Laboratory of Special Purpose Equipment and Advanced Manufacturing Technology, Ministry of Education, Zhejiang University of Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('浙江理工大学机械与自动控制学院', 'Faculty of Mechanical Engineering and automation, Zhejiang Sci‐Tech University');
INSERT INTO `常见工作单位规范写法` VALUES ('浙江省特种装备制造与先进加工技术重点实验室', 'Zhejiang Provincial Key Laboratory of Special Purpose Equipment and Advanced Manufacturing Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('清华大学机械工程系', 'Department of Mechanical Engineering, Tsinghua University');
INSERT INTO `常见工作单位规范写法` VALUES ('清华大学水利水电工程系', 'Department of Hydraulic Engineering, Tsinghua University');
INSERT INTO `常见工作单位规范写法` VALUES ('清华大学热能工程系', 'Department of Thermal Engineering, Tsinghua University');
INSERT INTO `常见工作单位规范写法` VALUES ('燕山大学机械工程学院', 'College of Mechanical Engineering, Yanshan University');
INSERT INTO `常见工作单位规范写法` VALUES ('燕山大学电气工程学院', 'School of Electrical Engineering, Yanshan University');
INSERT INTO `常见工作单位规范写法` VALUES ('甘肃农业大学工学院', 'School of Engineering, Gansu Agricultural University ');
INSERT INTO `常见工作单位规范写法` VALUES ('甘肃农业大学草业学院', 'Pratacultural College, Gansu Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('甘肃农业大学食品科学与工程学院              ', 'College of Food Science and Engineering，Gansu Agricultural University ');
INSERT INTO `常见工作单位规范写法` VALUES ('石河子大学信息科学与技术学院', 'College of Information Science and Technology, Shihezi University');
INSERT INTO `常见工作单位规范写法` VALUES ('石河子大学农学院', 'College of Agriculture, Shihezi University');
INSERT INTO `常见工作单位规范写法` VALUES ('石河子大学机械电气工程学院', 'College of Mechanical and Electrical Engineering, ShiHezi University,');
INSERT INTO `常见工作单位规范写法` VALUES ('石河子大学水利建筑工程学院', 'College of Water and Architectural Engineering, Shihezi University');
INSERT INTO `常见工作单位规范写法` VALUES ('福建农林大学园艺学院', 'College of Horticulture, Fujian Agriculture and Forestry University');
INSERT INTO `常见工作单位规范写法` VALUES ('福建农林大学林学院', 'College of Forestry, Fujian Agriculture and Forestry University');
INSERT INTO `常见工作单位规范写法` VALUES ('福建农林大学资源与环境学院', 'College of Resource and Environmental Science, Fujian Agriculture and Forestry University');
INSERT INTO `常见工作单位规范写法` VALUES ('福建农林大学食品科学学院', 'College of Food Science, Fujian Agriculture and Forestry University');
INSERT INTO `常见工作单位规范写法` VALUES ('装甲兵工程学院机械工程系', 'Department of Mechanical Engineering, Academy of Armored Force Engineering');
INSERT INTO `常见工作单位规范写法` VALUES ('西北农林科技大学中国旱区节水农业研究院', 'Institute of Water‐saving Agriculture in Arid Areas of China, Northwest A&F University');
INSERT INTO `常见工作单位规范写法` VALUES ('西北农林科技大学信息工程学院', 'College of Information Engineering, Northwest A&F University');
INSERT INTO `常见工作单位规范写法` VALUES ('西北农林科技大学农学院', 'College of Agronomy, Northwest A&F University');
INSERT INTO `常见工作单位规范写法` VALUES ('西北农林科技大学园艺学院', 'College of Horticulture, Northwest A&F University');
INSERT INTO `常见工作单位规范写法` VALUES ('西北农林科技大学旱区农业水土工程教育部重点实验室', 'The Key Laboratory of Agricultural Soil and Water Engineering in arid areas subordinated to the Ministry of Education');
INSERT INTO `常见工作单位规范写法` VALUES ('西北农林科技大学机械与电子工程学院', 'College of Mechanical and Electronic Engineering, Northwest A&F University');
INSERT INTO `常见工作单位规范写法` VALUES ('西北农林科技大学林学院', 'College of Forestry, Northwest A&F University');
INSERT INTO `常见工作单位规范写法` VALUES ('西北农林科技大学水利与建筑工程学院', 'College of Water Resources and Architectural Engineering, Northwest A&F University');
INSERT INTO `常见工作单位规范写法` VALUES ('西北农林科技大学水土保持研究所', 'Institute of Soil and Water Conservation, Northwest A&F University');
INSERT INTO `常见工作单位规范写法` VALUES ('西北农林科技大学葡萄酒学院', 'College of Enology, Northwest A&F University');
INSERT INTO `常见工作单位规范写法` VALUES ('西北农林科技大学资源环境学院', 'College of Natural Resources and Environment, Northwest A&F University');
INSERT INTO `常见工作单位规范写法` VALUES ('西北农林科技大学食品科学与工程学院', 'College of Food Science and Engineering, Northwest A&F University');
INSERT INTO `常见工作单位规范写法` VALUES ('西北工业大学机电学院', 'School of Mechanical Engineering, Northwestern Polytechnical University');
INSERT INTO `常见工作单位规范写法` VALUES ('西安理工大学机械与精密仪器工程学院', 'Faculty of Mechanical and Precision Instrument Engineering, Xi’an University of Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('西安理工大学水利水电学院', 'Faculty of Water Resources and Hydroelectric Engineering, Xi’an University of Technology');
INSERT INTO `常见工作单位规范写法` VALUES ('黑龙江八一农垦大学信息技术学院', 'College of Information Technology, Heilongjiang Bayi Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('黑龙江八一农垦大学工程学院', 'College of Engineering, Heilongjiang Bayi Agricultural University');
INSERT INTO `常见工作单位规范写法` VALUES ('黑龙江八一农垦大学食品学院', 'College of Food Science, Heilongjiang Bayi Agricultural University');
