INSERT INTO `软件名称规范写法` VALUES ('ANSYS');
INSERT INTO `软件名称规范写法` VALUES ('ArcGIS ');
INSERT INTO `软件名称规范写法` VALUES ('AutoCAD ');
INSERT INTO `软件名称规范写法` VALUES ('Design-Expert');
INSERT INTO `软件名称规范写法` VALUES ('EDEM');
INSERT INTO `软件名称规范写法` VALUES ('ENVI IDRIS');
INSERT INTO `软件名称规范写法` VALUES ('Excel ');
INSERT INTO `软件名称规范写法` VALUES ('Google Earth kernlab 软件包');
INSERT INTO `软件名称规范写法` VALUES ('LabVIEW');
INSERT INTO `软件名称规范写法` VALUES ('Matlab');
INSERT INTO `软件名称规范写法` VALUES ('Matlab/ Simulink ');
INSERT INTO `软件名称规范写法` VALUES ('OriginPro ');
INSERT INTO `软件名称规范写法` VALUES ('PASW Statistics ');
INSERT INTO `软件名称规范写法` VALUES ('Pro/Engineer ');
INSERT INTO `软件名称规范写法` VALUES ('random forests 软件包');
INSERT INTO `软件名称规范写法` VALUES ('SigmaPlot ');
INSERT INTO `软件名称规范写法` VALUES ('Solid45');
INSERT INTO `软件名称规范写法` VALUES ('Solid64');
INSERT INTO `软件名称规范写法` VALUES ('Solid95');
INSERT INTO `软件名称规范写法` VALUES ('Solidworks ');
INSERT INTO `软件名称规范写法` VALUES ('Spectral Cube ');
INSERT INTO `软件名称规范写法` VALUES ('Stateflow ');
INSERT INTO `软件名称规范写法` VALUES ('ViewSpecPro ');
INSERT INTO `软件名称规范写法` VALUES ('VS2D');
